project:
  type: website
  output-dir: docs

website:
  title: "Kelsey Warren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - bren_projects.qmd
      - phd_page.qmd
      - publications.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true
    page-layout: full

editor: visual

